name: ship_info_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  flutter_riverpod: ^2.4.0
  freezed_annotation: ^2.4.1
  webview_flutter: ^4.2.2
  json_annotation: any
  cupertino_icons: ^1.0.8
  flutter_inappwebview: ^6.0.0
  url_launcher: ^6.2.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  freezed: ^2.4.6
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.3.4
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
    - assets/splash.png

flutter_native_splash:
  color: "#ffffff"
  image: assets/splash.png
  android: true
  ios: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
